export 'package:flutter/material.dart';
export 'package:amazon/utils/global_variables.dart';
export 'package:amazon/utils/routers.dart';
export 'package:amazon/auth/screens/auth_screen.dart';
export 'package:amazon/utils/show_snakbar.dart';
export 'package:amazon/models/user.dart';
export 'package:amazon/utils/error_hanling.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'dart:convert';
export 'package:amazon/utils/custom_spacer.dart';
export 'package:amazon/auth/services/auth_services.dart';
export 'package:amazon/widgets/custom_text_feild.dart';
export 'package:amazon/widgets/custom_button.dart';
export 'package:amazon/providers/user_provider.dart';
export 'package:provider/provider.dart';
export 'package:amazon/auth/screens/home_screen.dart';
// export
// export
