export 'package:flutter/material.dart';
export 'package:amazon/utils/app_styles.dart';
export 'package:amazon/utils/routers.dart';
export 'package:amazon/auth/screens/auth_screen.dart';
export 'package:amazon/utils/show_snakbar.dart';
export 'package:amazon/models/user.dart';
export 'package:amazon/utils/error_hanling.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'dart:convert';
export 'package:amazon/utils/custom_spacer.dart';
export 'package:amazon/auth/services/auth_services.dart';
export 'package:amazon/widgets/custom_text_feild.dart';
export 'package:amazon/widgets/custom_button.dart';
export 'package:amazon/providers/user_provider.dart';
export 'package:provider/provider.dart';
export 'package:amazon/screens/User/home/home_screen.dart';
export 'package:amazon/screens/User/cart/cart_screen.dart';
export 'package:amazon/screens/User/profile/profile_screen.dart';
export 'package:amazon/screens/bottom_navigation_bar.dart';
export 'package:amazon/widgets/custom_spacer.dart';
export 'package:amazon/screens/User/profile/widgets/button_with_border.dart';
export 'package:amazon/screens/User/profile/widgets/below_app_bar.dart';
export 'package:amazon/screens/User/profile/widgets/list_view.dart';
export 'package:amazon/screens/User/profile/widgets/single_order.dart';
export 'package:amazon/screens/User/home/widgets/app_bar_search.dart';
export 'package:amazon/screens/User/home/widgets/order_type_row.dart';
export 'package:carousel_slider/carousel_slider.dart';
export 'package:amazon/screens/User/home/widgets/address_bar.dart';
export 'package:amazon/screens/User/home/widgets/crousel_images.dart';
export 'package:flutter/src/material/scaffold.dart';
export 'package:amazon/screens/User/home/widgets/deal_of_day.dart';
export 'package:amazon/screens/Admin/admin_bottom_navigation_bar.dart';
export 'package:amazon/screens/Admin/home/screens/admin_home_screen.dart';
export 'package:amazon/screens/Admin/home/screens/add_product.dart';
export 'package:dotted_border/dotted_border.dart';
export 'package:file_picker/file_picker.dart';
export 'dart:io';

export 'package:amazon/utils/file_picker.dart';
// export
// export
// export
